### ISSUE TITLE
how to retrieve the contents of .blend files

### ISSUE THREAD

**Issue by karawitan** [forensic-architecture/models#3]
Hello,

   thanks very much for your work.
Just curious, how to fetch the .blend files ?
As far I as see in the repository they look like external, git-lfs files:
```

kalou@shinwey:~/models$ cat 41/V2/Al\ Lataminah.blend 
version https://git-lfs.github.com/spec/v1
oid sha256:f436ed5df723ba62e05be3cbf6c8053e26ac3fb1943f5c2dcdf556ab3bcfdce8
size 16899004

```

Best Regards,

**Comment by breezykermo** [comment]
Hi there- you may need to install Git LFS before you clone the repository- [see here](https://git-lfs.github.com/). 

I'll make a note to update the README with an explanation, thanks for flagging that!

**Comment by karawitan** [comment]
Just tried to fetch all, 
unfortunatelly,the data is not available due to quota restrictions.

```
kalou@shinwey:~/models/34$ git lfs fetch --all
fetch: 14 object(s) found, done.                                                                                                                                                                              
fetch: Fetching all references...
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.                                                              
error: failed to fetch some objects from 'https://github.com/forensic-architecture/models.git/info/lfs'
```

**Comment by breezykermo** [comment]
@VupliDerts would you be comfortable making all the models we have in here available in the same way as the Beirut models? That way we won't hit this quota restriction.

**Comment by VupliDerts** [comment]
Yes, no problem, I'll endeavour to reformat these in the same way as with Beirut.

**Comment by VupliDerts** [comment]
Happy New Year! I've reformatted the 'models' repository and all large files are hosted externally so should be easier to access .blend files now.

**Comment by karawitan** [comment]
Thanks for you actions, happy new year !
However, the .blend files are still not accessible, due to the same error message, "repository is over its data quota"

```
kalou@shinwey:~/models$ git lfs fetch --all
fetch: 14 object(s) found, done.                                                                                                                                                                                   
fetch: Fetching all references...
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.                                                                   
error: failed to fetch some objects from 'https://github.com/forensic-architecture/models.git/info/lfs'

kalou@shinwey:~/models$ git log -1 --oneline
1ae9e81 (HEAD -> master, origin/master, origin/HEAD) Update README.md
```

**Comment by breezykermo** [comment]
Hi @berryamin - the files are no longer in this repo itself, but rather hosted on static storage elsewhere. @VupliDerts has updated the README files in each subdirectory with the appropriate links. So for the Latimah model, just follow the link in the [README](https://github.com/forensic-architecture/models/tree/master/41%20-%20Chemical%20Attacks%20in%20al%20Lataminah) to download the .blend file, which is [here](https://fa-public-assets.fra1.digitaloceanspaces.com/alLataminah/al%20Lataminah.blend).

**Comment by karawitan** [comment]
Ho yes thank you so much @breezykermo , it's working now. Git-lfs does not seem to be applicable anymore.
Best regards Sir !
