### ISSUE TITLE
Links missing or only pointing towards canisters in investigation #34

### ISSUE THREAD

**Issue by max1mvs** [forensic-architecture/models#4]
The collection of Blender files is missing, and the other download links are only referring to the "canisters only" file in [investigation #34](https://github.com/forensic-architecture/models/tree/master/34).

**Comment by VupliDerts** [comment]
Thanks for the comment. I've updated the links. Should be working now.

**Comment by max1mvs** [comment]
Sorry to bother you again, but the link to the collected files ([https://fa-public-assets.fra1.digitaloceanspaces.com/Douma/Chemical%20Attacks%20in%20Douma_3D%20Models.zip](https://fa-public-assets.fra1.digitaloceanspaces.com/Douma/Chemical%20Attacks%20in%20Douma_3D%20Models.zip)) seems to point towards an XML error file. I get the following error message when accessing the link (in multiple browsers & platforms):

`
This XML file does not appear to have any style information associated with it. The document tree is shown below
<Error>
	<Code>NoSuchKey</Code>
	<BucketName>fa-public-assets</BucketName>
	<RequestId>tx000000000000013af956d-0062fa1fd2-5c85f102-fra1b</RequestId>
	<HostId>5c85f102-fra1b-fra1-zg02</HostId>
</Error>
`

**Comment by VupliDerts** [comment]
Thanks for the follow up, updated again so should work now.
